In [1]:
import pandas as pd
import numpy as np

In [2]:
responses = pd.read_csv("../../data/raw/counterfactual_responses_raw.csv")

metadata = pd.read_csv("../../data/raw/metadata_raw.csv")

In [3]:
print(responses.shape)
print(metadata.shape)

(336, 9)
(56, 19)

In [ ]:
metadata.head()

,EXP,n,Participant_ID,Age,Gender,Kno_Level,Per_Level,Bilingual,Bi_Parents,Multi_Kno,Multi_Spk,Immersion,Prof_Need,Prof_Use,Motivation,Agent,Distractor,GN_Score,Difficulty
0,1,1,EXP1_01,25,0,6,7,0,1,0,1,0,1,1,4,1,4,23,3
1,1,2,EXP1_02,38,0,6,7,0,0,1,1,0,0,0,2,1,6,27,8
2,1,3,EXP1_03,27,1,4,5,0,1,1,1,0,1,1,6,1,4,28,7
3,1,4,EXP1_04,53,0,7,9,0,0,1,1,0,1,1,5,1,5,39,1
4,1,5,EXP1_05,53,1,7,8,0,0,1,1,1,1,1,4,1,6,35,1

In [5]:
responses.head()

,Partcipant_ID,Focus,Agent,Goal_Type,Item,Item_string,Item_len,Response_tag,Response
0,EXP1_01,I,1,no_goal,Item1,"""If I had heard the rainstorm, I would have fe...",11,L1_transfer_3,L1_transfer
1,EXP1_01,I,1,no_goal,Item2,"""If I had climbed the mountain cliff, I would ...",12,L1_transfer_3,L1_transfer
2,EXP1_01,I,1,goal_non_frequent,Item1,"""If I had created an online platform, I would ...",14,L1_transfer_3,L1_transfer
3,EXP1_01,I,1,goal_non_frequent,Item2,"""If I had invested in technology, I would have...",13,correct_3,correct
4,EXP1_01,I,1,goal_frequent,Item1,"""If I had saved money, I would have gone on ho...",11,correct_3,correct