Import libraries

# Consequent Reversibility Summary Tables
### Counts and Proportions for the combined group and for actors only.

Note: **consequent reversibility was finally removed from modelling** despite notebooks 15, 15_b, 15_c, 15_d and 16 as it was confounded with goal type in the theoretical subgroup. The 2 reversible conditions (goal_frequent and no_goal) kept showing to be very different profiles with very different redistribution patterns once agency was introduced; that's why it was discarded.

1. Overall Subgroup
2. Actors

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Read data and sanity checks

In [2]:
subgroup_theoretical = pd.read_csv("../../data/processed/subgroup_theoretical.csv")

In [3]:
subgroup_theoretical[
    [
        "Goal_Type",
        "Item",
        "Consequent_Reversibility"
    ]
].drop_duplicates()

           Goal_Type   Item Consequent_Reversibility
0            no_goal  Item1                      Yes
1            no_goal  Item2                      Yes
2  goal_non_frequent  Item1                       No
3  goal_non_frequent  Item2                       No
4      goal_frequent  Item1                      Yes
5      goal_frequent  Item2                      Yes

In [4]:
subgroup_theoretical.columns

Index(['Participant_ID', 'Focus', 'Agent', 'Goal_Type', 'Item', 'Item_string',
       'Item_len', 'Response_tag', 'Response', 'Response_Full', 'EXP', 'n',
       'Age', 'Gender', 'Kno_Level', 'Per_Level', 'Bilingual', 'Bi_Parents',
       'Multi_Kno', 'Multi_Spk', 'Immersion', 'Prof_Need', 'Prof_Use',
       'Motivation', 'Distractor', 'GN_Score', 'Difficulty', 'Kno_Level_Label',
       'Per_Level_Label', 'Prof_Need_Label', 'Prof_Use_Label',
       'Consequent_Reversibility'],
      dtype='str')

In [5]:
subgroup_theoretical.shape

(198, 32)

1. Overal Subgroup

Summary Table: responses proportions

In [6]:
response_props = pd.crosstab(
    [subgroup_theoretical["Goal_Type"], subgroup_theoretical["Agent"], subgroup_theoretical["Consequent_Reversibility"]],
    subgroup_theoretical["Response_Full"],
    normalize="index"
)

response_props

Response_Full                                     L1_transfer  L2_other  \
Goal_Type         Agent Consequent_Reversibility
goal_frequent     0     Yes                          0.309524  0.333333
                  1     Yes                          0.500000  0.083333
goal_non_frequent 0     No                           0.500000  0.214286
                  1     No                           0.666667  0.041667
no_goal           0     Yes                          0.547619  0.190476
                  1     Yes                          0.458333  0.166667

Response_Full                                      correct  missing_response
Goal_Type         Agent Consequent_Reversibility
goal_frequent     0     Yes                       0.333333          0.023810
                  1     Yes                       0.416667          0.000000
goal_non_frequent 0     No                        0.285714          0.000000
                  1     No                        0.291667          0.000000
no_goal           0     Yes                       0.214286          0.047619
                  1     Yes                       0.375000          0.000000

Summary Table: responses count

In [7]:
response_count = pd.crosstab(
    [subgroup_theoretical["Goal_Type"], subgroup_theoretical["Agent"], subgroup_theoretical["Consequent_Reversibility"]],
    subgroup_theoretical["Response_Full"]
)

response_count

Response_Full                                     L1_transfer  L2_other  \
Goal_Type         Agent Consequent_Reversibility
goal_frequent     0     Yes                                13        14
                  1     Yes                                12         2
goal_non_frequent 0     No                                 21         9
                  1     No                                 16         1
no_goal           0     Yes                                23         8
                  1     Yes                                11         4

Response_Full                                     correct  missing_response
Goal_Type         Agent Consequent_Reversibility
goal_frequent     0     Yes                            14                 1
                  1     Yes                            10                 0
goal_non_frequent 0     No                             12                 0
                  1     No                              7                 0
no_goal           0     Yes                             9                 2
                  1     Yes                             9                 0

- The apparent differences do not seem to be driven by tiny cells. 
- The differences L2 alternative cells once agent is introduced (goal frequent 14 --> 2; goal non frequent 9 ---> 1) are substantial.
- The no goal condition really seem to behave differently: agency doesn't seem to harm performance; if anything, it redistributes transfer while preserving conrrect responses.

In summary:
- The introduction of an agent appears to suppress L2 responses across all goal conditions. This effect is particularly pronounced in the goal_non_frequent condition, where L1 transfer becomes dominant and correct responses decrease.

### 2. Actors

In [8]:
subgroup_theoretical_actors = subgroup_theoretical[subgroup_theoretical["Focus"] == "I"].copy()

In [9]:
subgroup_theoretical_actors.shape

(120, 32)

Summary Table: responses proportions for Actors

In [10]:
response_props_a = pd.crosstab(
    [subgroup_theoretical_actors["Goal_Type"], subgroup_theoretical_actors["Agent"], subgroup_theoretical_actors["Consequent_Reversibility"]],
    subgroup_theoretical_actors["Response_Full"],
    normalize="index"
)

response_props_a

Response_Full                                     L1_transfer  L2_other  \
Goal_Type         Agent Consequent_Reversibility
goal_frequent     0     Yes                          0.250000  0.333333
                  1     Yes                          0.437500  0.125000
goal_non_frequent 0     No                           0.291667  0.333333
                  1     No                           0.687500  0.062500
no_goal           0     Yes                          0.541667  0.125000
                  1     Yes                          0.562500  0.125000

Response_Full                                     correct  missing_response
Goal_Type         Agent Consequent_Reversibility
goal_frequent     0     Yes                        0.3750          0.041667
                  1     Yes                        0.4375          0.000000
goal_non_frequent 0     No                         0.3750          0.000000
                  1     No                         0.2500          0.000000
no_goal           0     Yes                        0.2500          0.083333
                  1     Yes                        0.3125          0.000000

Summary Table: responses count for Actors

In [11]:
response_count_a = pd.crosstab(
    [subgroup_theoretical_actors["Goal_Type"], subgroup_theoretical_actors["Agent"], subgroup_theoretical_actors["Consequent_Reversibility"]],
    subgroup_theoretical_actors["Response_Full"]
)

response_count_a

Response_Full                                     L1_transfer  L2_other  \
Goal_Type         Agent Consequent_Reversibility
goal_frequent     0     Yes                                 6         8
                  1     Yes                                 7         2
goal_non_frequent 0     No                                  7         8
                  1     No                                 11         1
no_goal           0     Yes                                13         3
                  1     Yes                                 9         2

Response_Full                                     correct  missing_response
Goal_Type         Agent Consequent_Reversibility
goal_frequent     0     Yes                             9                 1
                  1     Yes                             7                 0
goal_non_frequent 0     No                              9                 0
                  1     No                              4                 0
no_goal           0     Yes                             6                 2
                  1     Yes                             5                 0

- The actor group is more structured. 
- Reversibility has surprisingly little effect when agency is absent, but becomes highly consequential when agency is explicit.