# Combined Subgroup: L2 Escape Model

Import Libraries

In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Combined Subgroup

1. Create escape_L2
2. Counts and Proportions
3. Logistic Models
    
    Main Effect Models:

    - E01: Focus
    - E02: Agent
    - E03: Goal_Type

    Additive Models:

    - E04: Focus + Agent
    - E05: Focus + Goal_Type
    - E06: Agent + Goal_Type

    Interactive Models:

    - E07: Focus * Agent
    - E08: Focus * Goal_Type
    - E09: Agent * Goal_Type
    - E10: Focus * Agent + Goal_Type
4. Model Comparisons
5. Summary Table

Read Data

In [90]:
subgroup_theoretical = pd.read_csv("../../data/processed/subgroup_theoretical.csv")

1. Create escape_2

Binary Outcome: responses that are not "L2_other" -those who managed to escape L2_other by choosing either a correct response or an L1_transfer response.

In [91]:
subgroup_theoretical["escape_L2"] = (
    subgroup_theoretical["Response_Full"] != "L2_other"
).astype(int)

2. Counts and Proportions

In [92]:
escape_L2_counts = pd.crosstab(
    subgroup_theoretical["escape_L2"],
    subgroup_theoretical["Response_Full"],
    margins = True)

escape_L2_counts

Response_Full  L1_transfer  L2_other  correct  missing_response  All
escape_L2
0                        0        38        0                 0   38
1                       96         0       61                 3  160
All                     96        38       61                 3  198

In [93]:
escape_L2_props = subgroup_theoretical["escape_L2"].value_counts(normalize = True)
escape_L2_props

escape_L2
1    0.808081
0    0.191919
Name: proportion, dtype: float64

From 198 observations, almost 80% of responses managed to escape L2_other options.

Counts and Proportions by Condition:

In [94]:
counts_condition = pd.crosstab(
    [subgroup_theoretical["Goal_Type"], subgroup_theoretical["Agent"], subgroup_theoretical["Focus"]],
    subgroup_theoretical["escape_L2"],
    margins = True)

counts_condition

escape_L2                       0    1  All
Goal_Type         Agent Focus
goal_frequent     0     I       8   16   24
                        They    6   12   18
                  1     I       2   14   16
                        They    0    8    8
goal_non_frequent 0     I       8   16   24
                        They    1   17   18
                  1     I       1   15   16
                        They    0    8    8
no_goal           0     I       3   21   24
                        They    5   13   18
                  1     I       2   14   16
                        They    2    6    8
All                            38  160  198

In [95]:
props_condition = pd.crosstab(
    [subgroup_theoretical["Goal_Type"], subgroup_theoretical["Agent"], subgroup_theoretical["Focus"]],
    subgroup_theoretical["escape_L2"],
    normalize= "index")

props_condition

escape_L2                             0         1
Goal_Type         Agent Focus
goal_frequent     0     I      0.333333  0.666667
                        They   0.333333  0.666667
                  1     I      0.125000  0.875000
                        They   0.000000  1.000000
goal_non_frequent 0     I      0.333333  0.666667
                        They   0.055556  0.944444
                  1     I      0.062500  0.937500
                        They   0.000000  1.000000
no_goal           0     I      0.125000  0.875000
                        They   0.277778  0.722222
                  1     I      0.125000  0.875000
                        They   0.250000  0.750000

3. Logistic Models

Import Libraries

In [96]:
import statsmodels.formula.api as smf
from scipy.stats import chi2

In [97]:
subgroup_theoretical["escape_L2"].value_counts()

escape_L2
1    160
0     38
Name: count, dtype: int64

**Main Effect Models**

**E01**

escape_L2 ~ Focus

In [98]:
E01 = smf.logit(
    "escape_L2 ~ Focus",
    data=subgroup_theoretical
    ).fit()

print(E01.summary())

Optimization terminated successfully.
         Current function value: 0.488668
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      196
Method:                           MLE   Df Model:                            1
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:               0.0006665
Time:                        19:01:03   Log-Likelihood:                -96.756
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                    0.7194
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         1.3863      0.228      6.074      0.000       0.939       1.834
Focus[T.They]     0.1335      0.373      0.358      0.720      -0.598       0.865
=================================================================================

Focus on its own cannot predict anything.

**E02**

escape_L2 ~ Agent

In [99]:
E2 = smf.logit(
    "escape_L2 ~ Agent",
    data= subgroup_theoretical
    ).fit()

print(E2.summary())

Optimization terminated successfully.
         Current function value: 0.471025
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      196
Method:                           MLE   Df Model:                            1
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                 0.03675
Time:                        19:01:03   Log-Likelihood:                -93.263
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                  0.007642
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.1199      0.207      5.414      0.000       0.714       1.525
Agent          1.1086      0.448      2.473      0.013       0.230       1.987
==============================================================================

Agency alone is strong.

**E03**

escape_L2 ~ Goal_Type

In [100]:
E03 = smf.logit(
    "escape_L2 ~ Goal_Type",
    data= subgroup_theoretical
    ).fit()

print(E03.summary())

Optimization terminated successfully.
         Current function value: 0.484442
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      195
Method:                           MLE   Df Model:                            2
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                0.009309
Time:                        19:01:03   Log-Likelihood:                -95.920
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                    0.4060
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                          1.1394      0.287      3.967      0.000       0.576       1.702
Goal_Type[T.goal_non_frequent]     0.5833      0.448      1.303      0.193      -0.294       1.461
Goal_Type[T.no_goal]               0.3646      0.429      0.849      0.396      -0.477       1.206
==================================================================================================

Goal Type on its alone predict anything.

**Additive Models**

**E04**

escape_L2 ~ Focus + Agent

In [101]:
E04 = smf.logit(
    "escape_L2 ~ Focus + Agent",
    data=subgroup_theoretical
    ).fit()

print(E04.summary())

Optimization terminated successfully.
         Current function value: 0.470088
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      195
Method:                           MLE   Df Model:                            2
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                 0.03866
Time:                        19:01:04   Log-Likelihood:                -93.077
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                   0.02367
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         1.0244      0.257      3.986      0.000       0.521       1.528
Focus[T.They]     0.2305      0.381      0.606      0.545      -0.515       0.977
Agent             1.1319      0.450      2.513      0.012       0.249       2.015
=================================================================================

Focus is not individually significant; however, adding it to Agency produces a good model. Thus, Focus does not predict escaping L2 options on its own but accounting for it does not erase the agency effect.

**E05**

escape_L2 ~ Focus + Goal_Type

In [102]:
E05 = smf.logit(
    "escape_L2 ~ Focus + Goal_Type",
    data=subgroup_theoretical
    ).fit()

print(E05.summary())

Optimization terminated successfully.
         Current function value: 0.484113
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      194
Method:                           MLE   Df Model:                            3
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                0.009981
Time:                        19:01:04   Log-Likelihood:                -95.854
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                    0.5865
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                          1.0875      0.320      3.396      0.001       0.460       1.715
Focus[T.They]                      0.1348      0.375      0.360      0.719      -0.600       0.869
Goal_Type[T.goal_non_frequent]     0.5837      0.448      1.304      0.192      -0.294       1.461
Goal_Type[T.no_goal]               0.3649      0.430      0.850      0.396      -0.477       1.207
==================================================================================================

As expected, neither predictor carries the model.

**E06**

escape_L2 ~ Agent + Goal_Type

In [103]:
E06 = smf.logit(
    "escape_L2 ~ Agent + Goal_Type",
    data=subgroup_theoretical
    ).fit()

print(E06.summary())

Optimization terminated successfully.
         Current function value: 0.466314
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      194
Method:                           MLE   Df Model:                            3
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                 0.04638
Time:                        19:01:04   Log-Likelihood:                -92.330
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                   0.02954
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                          0.8081      0.311      2.599      0.009       0.199       1.418
Goal_Type[T.goal_non_frequent]     0.6038      0.455      1.326      0.185      -0.289       1.496
Goal_Type[T.no_goal]               0.3785      0.437      0.865      0.387      -0.479       1.236
Agent                              1.1182      0.450      2.484      0.013       0.236       2.000
==================================================================================================

Interestingly, Goal Type so far did nothing on its own and nor when added to Focus; however, the additive model with Agency still works.

In [104]:
P01 = smf.logit(
    "escape_L2 ~ Focus + Agent + Goal_Type",
    data=subgroup_theoretical
    ).fit()

print(P01.summary())

Optimization terminated successfully.
         Current function value: 0.465367
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      193
Method:                           MLE   Df Model:                            4
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                 0.04832
Time:                        19:01:04   Log-Likelihood:                -92.143
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                   0.05278
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                          0.7109      0.348      2.043      0.041       0.029       1.393
Focus[T.They]                      0.2330      0.383      0.609      0.543      -0.517       0.983
Goal_Type[T.goal_non_frequent]     0.6050      0.456      1.327      0.184      -0.288       1.499
Goal_Type[T.no_goal]               0.3793      0.438      0.866      0.386      -0.479       1.238
Agent                              1.1418      0.452      2.524      0.012       0.255       2.028
==================================================================================================

**Interactive Models**

**E07**

escape_L2 ~ Focus * Agent

In [105]:
E07 = smf.logit(
    "escape_L2 ~ Focus * Agent",
    data=subgroup_theoretical
    ).fit()

print(E07.summary())

Optimization terminated successfully.
         Current function value: 0.470087
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      194
Method:                           MLE   Df Model:                            3
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                 0.03867
Time:                        19:01:04   Log-Likelihood:                -93.077
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                   0.05789
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               1.0259      0.267      3.836      0.000       0.502       1.550
Focus[T.They]           0.2269      0.423      0.537      0.591      -0.601       1.055
Agent                   1.1259      0.543      2.074      0.038       0.062       2.190
Focus[T.They]:Agent     0.0192      0.973      0.020      0.984      -1.888       1.927
=======================================================================================

Interaction Focus-Agency (They:Agent, p = 0.984) shows basically zero evidence for interaction. That simplifies interpretation.

**E08**

escape_L2 ~ Focus * Goal_Type

In [106]:
E08 = smf.logit(
    "escape_L2 ~ Focus * Goal_Type",
    data=subgroup_theoretical
    ).fit()

print(E08.summary())

Optimization terminated successfully.
         Current function value: 0.466260
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      192
Method:                           MLE   Df Model:                            5
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                 0.04649
Time:                        19:01:04   Log-Likelihood:                -92.319
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                    0.1090
================================================================================================================
                                                   coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
Intercept                                        1.0986      0.365      3.009      0.003       0.383       1.814
Focus[T.They]                                    0.1054      0.592      0.178      0.859      -1.054       1.265
Goal_Type[T.goal_non_frequent]                   0.1382      0.526      0.263      0.793      -0.893       1.169
Goal_Type[T.no_goal]                             0.8473      0.602      1.408      0.159      -0.332       2.026
Focus[T.They]:Goal_Type[T.goal_non_frequent]     1.8768      1.238      1.516      0.130      -0.550       4.304
Focus[T.They]:Goal_Type[T.no_goal]              -1.0527      0.880     -1.197      0.231      -2.777       0.672
================================================================================================================

Interaction Focus-Goal_Type non-frequent (They:goal_non_frequent) shows a large coefficient and a very high standard error. There could be something there but there is not enough precision.

**E09**

escape_L2 ~ Agent * Goal_Type

In [107]:
E09 = smf.logit(
    "escape_L2 ~ Agent * Goal_Type",
    data=subgroup_theoretical
    ).fit()

print(E09.summary())

Optimization terminated successfully.
         Current function value: 0.458893
         Iterations 7
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      192
Method:                           MLE   Df Model:                            5
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                 0.06156
Time:                        19:01:04   Log-Likelihood:                -90.861
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                   0.03590
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                                0.6931      0.327      2.118      0.034       0.052       1.335
Goal_Type[T.goal_non_frequent]           0.6061      0.499      1.216      0.224      -0.371       1.583
Goal_Type[T.no_goal]                     0.7538      0.511      1.474      0.141      -0.249       1.756
Agent                                    1.7047      0.808      2.110      0.035       0.121       3.288
Agent:Goal_Type[T.goal_non_frequent]     0.1315      1.356      0.097      0.923      -2.525       2.788
Agent:Goal_Type[T.no_goal]              -1.5422      1.052     -1.466      0.143      -3.604       0.520
========================================================================================================

Interaction Agent-Goal_Type still survives.

**E10**

escape_L2 ~ Focus * Agent + Goal_Type

In [108]:
E10 = smf.logit(
    "escape_L2 ~ Focus * Agent + Goal_Type",
    data=subgroup_theoretical
    ).fit()

print(E10.summary())

Optimization terminated successfully.
         Current function value: 0.465366
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:              escape_L2   No. Observations:                  198
Model:                          Logit   Df Residuals:                      192
Method:                           MLE   Df Model:                            5
Date:                Thu, 23 Jul 2026   Pseudo R-squ.:                 0.04832
Time:                        19:01:04   Log-Likelihood:                -92.142
converged:                       True   LL-Null:                       -96.821
Covariance Type:            nonrobust   LLR p-value:                   0.09566
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                          0.7123      0.356      2.001      0.045       0.015       1.410
Focus[T.They]                      0.2296      0.425      0.540      0.589      -0.604       1.063
Goal_Type[T.goal_non_frequent]     0.6050      0.456      1.327      0.184      -0.288       1.498
Goal_Type[T.no_goal]               0.3793      0.438      0.866      0.386      -0.479       1.238
Agent                              1.1362      0.545      2.084      0.037       0.068       2.205
Focus[T.They]:Agent                0.0179      0.976      0.018      0.985      -1.896       1.932
==================================================================================================

In the full additive with interaction model, Agency survives, Focus doesn't, Goal Type stays weak and interaction disappears. So, while it doesn't really work, consistency is valuable.

4. Model Comparisons

In [109]:
from scipy.stats import chi2

def lr_test(model_small, model_large):

    LR = 2 * (model_large.llf - model_small.llf)

    df = model_large.df_model - model_small.df_model

    p = chi2.sf(LR, df)

    return pd.Series({
        "LR": LR,
        "df": df,
        "p_value": p
    })

**Behavioural hierarchy**

Focus (E01)

↓

Focus + Agent (E04)

In [110]:
lr_test(E01, E04)

LR         7.357726
df         1.000000
p_value    0.006678
dtype: float64

Focus (E01)

↓

Focus + Agent + Goal_Type (P01)

In [111]:
lr_test(E01, P01)

LR         9.227303
df         3.000000
p_value    0.026417
dtype: float64

Focus + Agent (E04)

↓

Focus + Agent + Goal_Type (P01)

In [112]:
lr_test(E04, P01)

LR         1.869577
df         2.000000
p_value    0.392669
dtype: float64

**Interaction hierarchy**

Focus + Agent (E04)

↓

Focus * Agent (E07)

In [113]:
lr_test(E04, E07)

LR         0.000391
df         1.000000
p_value    0.984231
dtype: float64

Focus + Goal_Type (E05)

↓

Focus * Goal_Type (E08)

In [114]:
lr_test(E05, E08)

LR         7.069788
df         2.000000
p_value    0.029162
dtype: float64

Agent + Goal_Type (E06)

↓

Agent * Goal_Type (E09)

In [115]:
lr_test(E06, E09)

LR         2.938946
df         2.000000
p_value    0.230047
dtype: float64

5. Summary Table

In [116]:
goal_behaviour = ["Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined"]

model_name = ["E01", "E02", "E03", "E03", "E04", "E04", "E05", "E05", "E05", "E06", "E06", "E06", "E07", "E07", "E07", "E08", "E08", "E08", "E08", "E08", "E09", "E09", "E09", "E09", "E09", "E10", "E10", "E10", "E10", "E10"]

outcome = ["Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2", "Escape_L2"]

formula = ["escape_L2 ~ Focus", "escape_L2 ~ Agent", "escape_L2 ~ Goal_Type", "escape_L2 ~ Goal_Type", "escape_L2 ~ Focus + Agent", "escape_L2 ~ Focus + Agent", "escape_L2 ~ Focus + Goal_Type","escape_L2 ~ Focus + Goal_Type", "escape_L2 ~ Focus + Goal_Type", "escape_L2 ~ Agent + Goal_Type", "escape_L2 ~ Agent + Goal_Type", "escape_L2 ~ Agent + Goal_Type", "escape_L2 ~ Focus * Agent", "escape_L2 ~ Focus * Agent", "escape_L2 ~ Focus * Agent", "escape_L2 ~ Focus * Goal_Type", "escape_L2 ~ Focus * Goal_Type", "escape_L2 ~ Focus * Goal_Type", "escape_L2 ~ Focus * Goal_Type", "escape_L2 ~ Focus * Goal_Type", "escape_L2 ~ Agent * Goal_Type", "escape_L2 ~ Agent * Goal_Type", "escape_L2 ~ Agent * Goal_Type", "escape_L2 ~ Agent * Goal_Type", "escape_L2 ~ Agent * Goal_Type", "escape_L2 ~ Focus * Agent + Goal_Type", "escape_L2 ~ Focus * Agent + Goal_Type", "escape_L2 ~ Focus * Agent + Goal_Type", "escape_L2 ~ Focus * Agent + Goal_Type", "escape_L2 ~ Focus * Agent + Goal_Type"]

predictor= ["They", "Agent", "goal_non_frequent", "no_goal", "They", "Agent", "They", "goal_non_frequent", "no_goal", "goal_non_frequent", "no_goal", "Agent", "They", "Agent", "They:Agent", "They", "goal_non_frequent", "no_goal", "They:goal_non_frequent", "They:no_goal", "goal_non_frequent", "no_goal", "Agent", "Agent:goal_non_frequent", "Agent:no_goal", "They", "goal_non_frequent", "no_goal", "Agent", "They:Agent"]

coef = [0.1335, 1.1086, 0.5833, 0.3646, 0.2305, 1.1319, 0.1348, 0.5837, 0.3649, 0.6038, 0.3785, 1.1182, 0.2269, 1.1259, 0.0192, 0.1054, 0.1382, 0.8473, 1.8768, -1.0527, 0.6061, 0.7538, 1.7047, 0.1315, -1.5422, 0.2296, 0.6050, 0.3793, 1.1362, 0.0179]

std_error =[0.373, 0.448, 0.448, 0.429, 0.381, 0.450, 0.375, 0.448, 0.430, 0.455, 0.437, 0.450, 0.423, 0.543, 0.973, 0.592, 0.526, 0.602, 1.238, 0.880, 0.499, 0.511, 0.808, 1.356, 1.052, 0.425, 0.456, 0.438, 0.545, 0.976]

coef_p = [0.720, 0.013, 0.193, 0.396, 0.545, 0.012, 0.719, 0.192, 0.396, 0.185, 0.387, 0.013, 0.591, 0.038, 0.984, 0.859, 0.793, 0.159, 0.130, 0.231, 0.224, 0.141, 0.035, 0.923, 0.143, 0.589, 0.184, 0.386, 0.037, 0.985]

LLR_p = [0.7194, 0.007642, 0.4060, 0.4060,  0.02367, 0.02367, 0.5865, 0.5865, 0.5865, 0.02954, 0.02954, 0.02954, 0.05789, 0.05789, 0.05789, 0.1090, 0.1090, 0.1090, 0.1090, 0.1090, 0.03590, 0.03590, 0.03590, 0.03590, 0.03590, 0.09566, 0.09566, 0.09566, 0.09566, 0.09566]

observations= [198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198, 198]

In [117]:
escape_summary = pd.DataFrame({
    "Goal_Behaviour": goal_behaviour,
    "Model": model_name,
    "Outcome": outcome,
    "Formula": formula, 
    "Predictor": predictor,
    "Coef": coef,
    "Std_err": std_error,
    "Coef_p": coef_p,
    "Model_LLR_p": LLR_p,
    "N": observations
})

escape_summary

,Goal_Behaviour,Model,Outcome,Formula,Predictor,Coef,Std_err,Coef_p,Model_LLR_p,N
0,Combined,E01,Escape_L2,escape_L2 ~ Focus,They,0.1335,0.373,0.720,0.719400,198
1,Combined,E02,Escape_L2,escape_L2 ~ Agent,Agent,1.1086,0.448,0.013,0.007642,198
2,Combined,E03,Escape_L2,escape_L2 ~ Goal_Type,goal_non_frequent,0.5833,0.448,0.193,0.406000,198
3,Combined,E03,Escape_L2,escape_L2 ~ Goal_Type,no_goal,0.3646,0.429,0.396,0.406000,198
4,Combined,E04,Escape_L2,escape_L2 ~ Focus + Agent,They,0.2305,0.381,0.545,0.023670,198
5,Combined,E04,Escape_L2,escape_L2 ~ Focus + Agent,Agent,1.1319,0.450,0.012,0.023670,198
6,Combined,E05,Escape_L2,escape_L2 ~ Focus + Goal_Type,They,0.1348,0.375,0.719,0.586500,198
7,Combined,E05,Escape_L2,escape_L2 ~ Focus + Goal_Type,goal_non_frequent,0.5837,0.448,0.192,0.586500,198
8,Combined,E05,Escape_L2,escape_L2 ~ Focus + Goal_Type,no_goal,0.3649,0.430,0.396,0.586500,198
9,Combined,E06,Escape_L2,escape_L2 ~ Agent + Goal_Type,goal_non_frequent,0.6038,0.455,0.185,0.029540,198
10,Combined,E06,Escape_L2,escape_L2 ~ Agent + Goal_Type,no_goal,0.3785,0.437,0.387,0.029540,198
11,Combined,E06,Escape_L2,escape_L2 ~ Agent + Goal_Type,Agent,1.1182,0.450,0.013,0.029540,198
12,Combined,E07,Escape_L2,escape_L2 ~ Focus * Agent,They,0.2269,0.423,0.591,0.057890,198
13,Combined,E07,Escape_L2,escape_L2 ~ Focus * Agent,Agent,1.1259,0.543,0.038,0.057890,198
14,Combined,E07,Escape_L2,escape_L2 ~ Focus * Agent,They:Agent,0.0192,0.973,0.984,0.057890,198
15,Combined,E08,Escape_L2,escape_L2 ~ Focus * Goal_Type,They,0.1054,0.592,0.859,0.109000,198
16,Combined,E08,Escape_L2,escape_L2 ~ Focus * Goal_Type,goal_non_frequent,0.1382,0.526,0.793,0.109000,198
17,Combined,E08,Escape_L2,escape_L2 ~ Focus * Goal_Type,no_goal,0.8473,0.602,0.159,0.109000,198
18,Combined,E08,Escape_L2,escape_L2 ~ Focus * Goal_Type,They:goal_non_frequent,1.8768,1.238,0.130,0.109000,198
19,Combined,E08,Escape_L2,escape_L2 ~ Focus * Goal_Type,They:no_goal,-1.0527,0.880,0.231,0.109000,198
20,Combined,E09,Escape_L2,escape_L2 ~ Agent * Goal_Type,goal_non_frequent,0.6061,0.499,0.224,0.035900,198
21,Combined,E09,Escape_L2,escape_L2 ~ Agent * Goal_Type,no_goal,0.7538,0.511,0.141,0.035900,198
22,Combined,E09,Escape_L2,escape_L2 ~ Agent * Goal_Type,Agent,1.7047,0.808,0.035,0.035900,198
23,Combined,E09,Escape_L2,escape_L2 ~ Agent * Goal_Type,Agent:goal_non_frequent,0.1315,1.356,0.923,0.035900,198
24,Combined,E09,Escape_L2,escape_L2 ~ Agent * Goal_Type,Agent:no_goal,-1.5422,1.052,0.143,0.035900,198
25,Combined,E10,Escape_L2,escape_L2 ~ Focus * Agent + Goal_Type,They,0.2296,0.425,0.589,0.095660,198
26,Combined,E10,Escape_L2,escape_L2 ~ Focus * Agent + Goal_Type,goal_non_frequent,0.6050,0.456,0.184,0.095660,198
27,Combined,E10,Escape_L2,escape_L2 ~ Focus * Agent + Goal_Type,no_goal,0.3793,0.438,0.386,0.095660,198
28,Combined,E10,Escape_L2,escape_L2 ~ Focus * Agent + Goal_Type,Agent,1.1362,0.545,0.037,0.095660,198
29,Combined,E10,Escape_L2,escape_L2 ~ Focus * Agent + Goal_Type,They:Agent,0.0179,0.976,0.985,0.095660,198


- Focus: perspective is not enough on its own but including it changes the modeling landscape enough for additive models to become informative. Focus seems to explain some of the residual variability

- Agency: explicit agency remains the most dominatn predictor for escaping L2_other responses

- the fact that additive models are better than interactive models show that, consistently, no model is better if the effect of one predictor depends on the level of another one but rather points at predictors contributing independently.