# Resolution: Correct Response Model

Consequent Reversibility was not included in the final escape models because, in this subgroup structure, it is partially encoded by Goal_Type and produced unstable estimates when entered together with Goal_Type.

Import Libraries

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Overall Subgroup
This subset of data explores observations when _Focus_ = I and _Focus_= They.
1. Create resolved_correct
2. Counts and Proportions
3. Logistic Models
    - RC1: Agency
    - RC2: Goal Type
    - RC3: Additive Model
    - RC4: Interactive Model 
4. Model Comparison
5. Summary Table

Read Data

In [39]:
subgroup_theoretical = pd.read_csv("../../data/processed/subgroup_theoretical.csv")

1. Create resolved_correct

Binary Outcome: include correct responses from escape_L2 observations.

In [40]:
subgroup_theoretical["escape_L2"] = (
    subgroup_theoretical["Response_Full"] != "L2_other"
).astype(int)

In [41]:
escapees = subgroup_theoretical[subgroup_theoretical["escape_L2"] == 1].copy()

In [42]:
escapees["resolved_correct"] = (escapees["Response_Full"] == "correct").astype(int)

2. Counts and Proportions

In [43]:
resolved_correct_counts = pd.crosstab(
    escapees["resolved_correct"],
    escapees["Response_Full"])

resolved_correct_counts

Response_Full     L1_transfer  correct  missing_response
resolved_correct
0                          96        0                 3
1                           0       61                 0

In [44]:
resolved_correct_props = escapees["resolved_correct"].value_counts(normalize = True)
resolved_correct_props

resolved_correct
0    0.61875
1    0.38125
Name: proportion, dtype: float64

From 160 observations, almost 38% of responses that had escaped *L2_other* options were resolved correctly.

Counts and Proportions by Condition:

In [45]:
counts_condition = pd.crosstab(
    [escapees["Goal_Type"], escapees["Agent"]],
    escapees["resolved_correct"],
    margins = True)

counts_condition

resolved_correct          0   1  All
Goal_Type         Agent
goal_frequent     0      14  14   28
                  1      12  10   22
goal_non_frequent 0      21  12   33
                  1      16   7   23
no_goal           0      25   9   34
                  1      11   9   20
All                      99  61  160

In [46]:
props_condition = pd.crosstab(
    [escapees["Goal_Type"], escapees["Agent"]],
    escapees["resolved_correct"],
    normalize= "index")

props_condition

resolved_correct                0         1
Goal_Type         Agent
goal_frequent     0      0.500000  0.500000
                  1      0.545455  0.454545
goal_non_frequent 0      0.636364  0.363636
                  1      0.695652  0.304348
no_goal           0      0.735294  0.264706
                  1      0.550000  0.450000

COMMENT GENERAL PROPORTIONS

3. Logistic Models

Import Libraries

In [47]:
import statsmodels.formula.api as smf
from scipy.stats import chi2

In [48]:
escapees["resolved_correct"].value_counts()

resolved_correct
0    99
1    61
Name: count, dtype: int64

**Model RC1**

resolved_correct ~ Agent

In [49]:
RC1 = smf.logit(
    "resolved_correct ~ Agent",
    data=escapees
    ).fit()

print(RC1.summary())

Optimization terminated successfully.
         Current function value: 0.664164
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      158
Method:                           MLE   Df Model:                            1
Date:                Sun, 05 Jul 2026   Pseudo R-squ.:               0.0007657
Time:                        16:41:23   Log-Likelihood:                -106.27
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.6865
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.5390      0.213     -2.534      0.011      -0.956      -0.122
Agent          0.1335      0.331      0.404      0.686      -0.515       0.782
==============================================================================

**Model RC2**

resolved_correct ~ Goal_Type

In [50]:
RC2 = smf.logit(
    "resolved_correct ~ Goal_Type",
    data= escapees
    ).fit()

print(RC2.summary())

Optimization terminated successfully.
         Current function value: 0.655378
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      157
Method:                           MLE   Df Model:                            2
Date:                Sun, 05 Jul 2026   Pseudo R-squ.:                 0.01398
Time:                        16:41:23   Log-Likelihood:                -104.86
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.2260
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         -0.0800      0.283     -0.283      0.777      -0.635       0.475
Goal_Type[T.goal_non_frequent]    -0.5864      0.400     -1.467      0.142      -1.370       0.197
Goal_Type[T.no_goal]              -0.6131      0.404     -1.516      0.129      -1.406       0.179
==================================================================================================

**Model RC3**

resolved_correct ~ Agent + Goal_Type

In [51]:
RC3 = smf.logit(
    "resolved_correct ~ Agent + Goal_Type",
    data= escapees
    ).fit()

print(RC3.summary())

Optimization terminated successfully.
         Current function value: 0.655049
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      156
Method:                           MLE   Df Model:                            3
Date:                Sun, 05 Jul 2026   Pseudo R-squ.:                 0.01448
Time:                        16:41:23   Log-Likelihood:                -104.81
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.3795
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         -0.1279      0.319     -0.401      0.689      -0.754       0.498
Goal_Type[T.goal_non_frequent]    -0.5837      0.400     -1.459      0.144      -1.368       0.200
Goal_Type[T.no_goal]              -0.6059      0.405     -1.496      0.135      -1.400       0.188
Agent                              0.1086      0.334      0.325      0.745      -0.547       0.764
==================================================================================================

**Model RC4**

resolved_correct ~ Agent * Goal_Type

In [52]:
RC4 = smf.logit(
    "resolved_correct ~ Agent * Goal_Type",
    data=escapees
    ).fit()

print(RC4.summary())

Optimization terminated successfully.
         Current function value: 0.648393
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      154
Method:                           MLE   Df Model:                            5
Date:                Sun, 05 Jul 2026   Pseudo R-squ.:                 0.02449
Time:                        16:41:23   Log-Likelihood:                -103.74
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.3909
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                            -5.629e-17      0.378  -1.49e-16      1.000      -0.741       0.741
Goal_Type[T.goal_non_frequent]          -0.5596      0.523     -1.069      0.285      -1.585       0.466
Goal_Type[T.no_goal]                    -1.0217      0.542     -1.884      0.060      -2.084       0.041
Agent                                   -0.1823      0.571     -0.319      0.750      -1.302       0.937
Agent:Goal_Type[T.goal_non_frequent]    -0.0847      0.814     -0.104      0.917      -1.680       1.511
Agent:Goal_Type[T.no_goal]               1.0033      0.824      1.217      0.223      -0.612       2.619
========================================================================================================

4. Model Comparisons

In [53]:
from scipy.stats import chi2

def lr_test(model_small, model_large):

    LR = 2 * (model_large.llf - model_small.llf)

    df = model_large.df_model - model_small.df_model

    p = chi2.sf(LR, df)

    return pd.Series({
        "LR": LR,
        "df": df,
        "p_value": p
    })

In [54]:
lr_test(RC1, RC3)

LR         2.916765
df         2.000000
p_value    0.232612
dtype: float64

In [55]:
lr_test(RC1, RC4)

LR         5.046581
df         4.000000
p_value    0.282551
dtype: float64

5. Summary Table

In [68]:
model_name = ["RC1", "RC2", "RC2", "RC3", "RC3", "RC3", "RC4", "RC4", "RC4", "RC4", "RC4"]

outcome = ["resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct"]

subgroup = ["Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall"]

formula = ["resolved_correct ~ Agent", "resolved_correct ~ Goal_Type", "resolved_correct ~ Goal_Type", "resolved_correct ~ Agent + Goal_Type", "resolved_correct ~ Agent + Goal_Type", "resolved_correct ~ Agent + Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type"]

predictor= ["Agent", "goal_non_frequent", "no_goal", "goal_non_frequent", "no_goal", "Agent",  "goal_non_frequent", "no_goal", "Agent", "Agent:goal_non_frequent", "Agent:no_goal"]

coef = [0.1335, -0.5864, -0.6131, -0.5837, -0.6059, 0.1086, -0.5596, -1.0217, -0.1823, -0.0847, 1.0033]

coef_p = [0.686, 0.142, 0.129, 0.144, 0.135, 0.745, 0.285, 0.060, 0.750, 0.917, 0.223]

LLR_p = [0.6865, 0.2260, 0.2260, 0.3795, 0.3795, 0.3795, 0.3909, 0.3909, 0.3909, 0.3909, 0.3909]

observations= [160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160]

Takeaway = []

In [69]:
correct_summary_overall = pd.DataFrame({
    "Model": model_name,
    "Outcome": outcome,
    "Subgroup": subgroup,
    "Formula": formula, 
    "Predictor": predictor,
    "Coef": coef,
    "Coef_p": coef_p,
    "Model_LLR_p": LLR_p,
    "N": observations
})

correct_summary_overall

,Model,Outcome,Subgroup,Formula,Predictor,Coef,Coef_p,Model_LLR_p,N
0,RC1,resolved_correct,Overall,resolved_correct ~ Agent,Agent,0.1335,0.686,0.6865,160
1,RC2,resolved_correct,Overall,resolved_correct ~ Goal_Type,goal_non_frequent,-0.5864,0.142,0.2260,160
2,RC2,resolved_correct,Overall,resolved_correct ~ Goal_Type,no_goal,-0.6131,0.129,0.2260,160
3,RC3,resolved_correct,Overall,resolved_correct ~ Agent + Goal_Type,goal_non_frequent,-0.5837,0.144,0.3795,160
4,RC3,resolved_correct,Overall,resolved_correct ~ Agent + Goal_Type,no_goal,-0.6059,0.135,0.3795,160
5,RC3,resolved_correct,Overall,resolved_correct ~ Agent + Goal_Type,Agent,0.1086,0.745,0.3795,160
6,RC4,resolved_correct,Overall,resolved_correct ~ Agent * Goal_Type,goal_non_frequent,-0.5596,0.285,0.3909,160
7,RC4,resolved_correct,Overall,resolved_correct ~ Agent * Goal_Type,no_goal,-1.0217,0.060,0.3909,160
8,RC4,resolved_correct,Overall,resolved_correct ~ Agent * Goal_Type,Agent,-0.1823,0.750,0.3909,160
9,RC4,resolved_correct,Overall,resolved_correct ~ Agent * Goal_Type,Agent:goal_non_frequent,-0.0847,0.917,0.3909,160
10,RC4,resolved_correct,Overall,resolved_correct ~ Agent * Goal_Type,Agent:no_goal,1.0033,0.223,0.3909,160

## Actors Subgroup
This subset of data explores observations only when _Focus_ = I.
1. Create resolved_correct
2. Counts and Proportions
3. Logistic Models
    - RC1_A: Agency
    - RC2_A: Goal Type
    - RC3_A: Additive Model
    - RC4_A: Interactive Model 
4. Model Comparison
5. Summary Table

Read Data

In [ ]:
subgroup_actors = subgroup_theoretical[subgroup_theoretical["Focus"] == "I"].copy()

1. Create resolved_correct

Binary Outcome: include correct responses from escape_L2 observations within actors.

In [ ]:
subgroup_actors["escape_L2"] = (
    subgroup_actors["Response_Full"] != "L2_other"
).astype(int)

In [ ]:
escapees_actors = subgroup_actors[subgroup_actors["escape_L2"] == 1].copy()

In [ ]:
escapees_actors["resolved_correct"] = (escapees_actors["Response_Full"] == "correct").astype(int)

2. Counts and Proportions

In [ ]:
resolved_correct_counts = pd.crosstab(
    escapees_actors["resolved_correct"],
    escapees_actors["Response_Full"])

resolved_correct_counts

Response_Full     L1_transfer  correct  missing_response
resolved_correct
0                          53        0                 3
1                           0       40                 0

In [ ]:
resolved_correct_props = escapees_actors["resolved_correct"].value_counts(normalize = True)
resolved_correct_props

resolved_correct
0    0.583333
1    0.416667
Name: proportion, dtype: float64

From 96 actors' observations (from the original 160), almost 41% of responses that managed to escape *L2_other* options were resolved correctly.

Counts and Proportions by Condition:

In [ ]:
counts_condition = pd.crosstab(
    [escapees_actors["Goal_Type"], escapees_actors["Agent"]],
    escapees_actors["resolved_correct"],
    margins = True)

counts_condition

resolved_correct          0   1  All
Goal_Type         Agent
goal_frequent     0       7   9   16
                  1       7   7   14
goal_non_frequent 0       7   9   16
                  1      11   4   15
no_goal           0      15   6   21
                  1       9   5   14
All                      56  40   96

In [ ]:
props_condition = pd.crosstab(
    [escapees_actors["Goal_Type"], escapees_actors["Agent"]],
    escapees_actors["resolved_correct"],
    normalize= "index")

props_condition

resolved_correct                0         1
Goal_Type         Agent
goal_frequent     0      0.437500  0.562500
                  1      0.500000  0.500000
goal_non_frequent 0      0.437500  0.562500
                  1      0.733333  0.266667
no_goal           0      0.714286  0.285714
                  1      0.642857  0.357143

ADD COMMENT ON GENERAL PROPORTIONS

3. Logistic Models

In [ ]:
escapees_actors["resolved_correct"].value_counts()

resolved_correct
0    56
1    40
Name: count, dtype: int64

**RC1_A Model** 

resolved_correct ~ Agent

In [ ]:
RC1_A = smf.logit(
    "resolved_correct ~ Agent",
    data=escapees_actors
    ).fit()

print(RC1_A.summary())

Optimization terminated successfully.
         Current function value: 0.675867
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                   96
Model:                          Logit   Df Residuals:                       94
Method:                           MLE   Df Model:                            1
Date:                Sun, 05 Jul 2026   Pseudo R-squ.:                0.004898
Time:                        16:23:44   Log-Likelihood:                -64.883
converged:                       True   LL-Null:                       -65.203
Covariance Type:            nonrobust   LLR p-value:                    0.4242
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.1892      0.276     -0.686      0.493      -0.730       0.352
Agent         -0.3340      0.419     -0.797      0.426      -1.156       0.488
==============================================================================

**RC2_A Model** 

resolved_correct ~  Goal_Type

In [ ]:
RC2_A = smf.logit(
    "resolved_correct ~ Goal_Type",
    data=escapees_actors
    ).fit()

print(RC2_A.summary())

Optimization terminated successfully.
         Current function value: 0.662472
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                   96
Model:                          Logit   Df Residuals:                       93
Method:                           MLE   Df Model:                            2
Date:                Sun, 05 Jul 2026   Pseudo R-squ.:                 0.02462
Time:                        16:23:44   Log-Likelihood:                -63.597
converged:                       True   LL-Null:                       -65.203
Covariance Type:            nonrobust   LLR p-value:                    0.2008
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                          0.1335      0.366      0.365      0.715      -0.584       0.851
Goal_Type[T.goal_non_frequent]    -0.4590      0.516     -0.889      0.374      -1.471       0.553
Goal_Type[T.no_goal]              -0.9137      0.516     -1.770      0.077      -1.926       0.098
==================================================================================================

**RC3_A Model**

resolved_correct ~  Agent + Goal_Type

In [ ]:
RC3_A = smf.logit(
    "resolved_correct ~ Agent + Goal_Type",
    data=escapees_actors
    ).fit()

print(RC3_A.summary())

Optimization terminated successfully.
         Current function value: 0.658087
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                   96
Model:                          Logit   Df Residuals:                       92
Method:                           MLE   Df Model:                            3
Date:                Sun, 05 Jul 2026   Pseudo R-squ.:                 0.03108
Time:                        16:23:44   Log-Likelihood:                -63.176
converged:                       True   LL-Null:                       -65.203
Covariance Type:            nonrobust   LLR p-value:                    0.2559
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                          0.3175      0.420      0.756      0.449      -0.505       1.140
Goal_Type[T.goal_non_frequent]    -0.4565      0.519     -0.880      0.379      -1.473       0.560
Goal_Type[T.no_goal]              -0.9480      0.521     -1.821      0.069      -1.968       0.072
Agent                             -0.3917      0.429     -0.914      0.361      -1.232       0.449
==================================================================================================

**RC4_A Model**

resolved_correct ~ Agent * Goal_Type

In [ ]:
RC4_A = smf.logit(
    "resolved_correct ~ Agent * Goal_Type",
    data= escapees_actors
    ).fit()

print(RC4_A.summary())

Optimization terminated successfully.
         Current function value: 0.646053
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                   96
Model:                          Logit   Df Residuals:                       90
Method:                           MLE   Df Model:                            5
Date:                Sun, 05 Jul 2026   Pseudo R-squ.:                 0.04879
Time:                        16:23:44   Log-Likelihood:                -62.021
converged:                       True   LL-Null:                       -65.203
Covariance Type:            nonrobust   LLR p-value:                    0.2725
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                                0.2513      0.504      0.499      0.618      -0.736       1.239
Goal_Type[T.goal_non_frequent]        6.475e-16      0.713   9.09e-16      1.000      -1.397       1.397
Goal_Type[T.no_goal]                    -1.1676      0.698     -1.673      0.094      -2.536       0.201
Agent                                   -0.2513      0.735     -0.342      0.732      -1.691       1.189
Agent:Goal_Type[T.goal_non_frequent]    -1.0116      1.065     -0.950      0.342      -3.099       1.076
Agent:Goal_Type[T.no_goal]               0.5798      1.041      0.557      0.578      -1.461       2.621
========================================================================================================

4. Model comparisons

In [ ]:
lr_test(RC1_A, RC3_A)

LR         3.413761
df         2.000000
p_value    0.181431
dtype: float64

In [ ]:
lr_test(RC1_A, RC4_A)

LR         5.724189
df         4.000000
p_value    0.220715
dtype: float64

5. Summary Table

correct_summary_actors

In [70]:
model_name = ["RC1_A", "RC2_A", "RC2_A", "RC3_A", "RC3_A", "RC3_A", "RC4_A", "RC4_A", "RC4_A", "RC4_A", "RC4_A"]

outcome = ["resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct"]

subgroup = ["Actors", "Actors", "Actors", "Actors", "Actors", "Actors", "Actors", "Actors", "Actors", "Actors", "Actors"]

formula = ["resolved_correct ~ Agent", "resolved_correct ~ Goal_Type", "resolved_correct ~ Goal_Type", "resolved_correct ~ Agent + Goal_Type", "resolved_correct ~ Agent + Goal_Type", "resolved_correct ~ Agent + Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type"]

predictor= ["Agent", "goal_non_frequent", "no_goal", "goal_non_frequent", "no_goal", "Agent",  "goal_non_frequent", "no_goal", "Agent", "Agent:goal_non_frequent", "Agent:no_goal"]

coef = [-0.3340, -0.4590, -0.9137, -0.4565, -0.9480, -0.3917, 6.475e-16, -1.1676, -0.2513, -1.0116, 0.5798]

std_error= [0.419, 0.516, 0.516, 0.519, 0.521, 0.429, 0.713, 0.698, 0.735, 1.065, 1.041]

coef_p = [0.426, 0.374, 0.077, 0.379, 0.069, 0.361, 1.000, 0.094, 0.732, 0.342, 0.578]

LLR_p = [0.4242, 0.2008, 0.2008, 0.2559, 0.2559, 0.2559, 0.2725, 0.2725, 0.2725, 0.2725, 0.2725]

observations = [96, 96, 96, 96, 96, 96, 96, 96, 96, 96, 96]

Takeaway = []

In [71]:
correct_summary_actors = pd.DataFrame({
    "Model": model_name,
    "Outcome": outcome,
    "Subgroup": subgroup,
    "Formula": formula, 
    "Predictor": predictor,
    "Coef": coef,
    "Std_err": std_error,
    "Coef_p": coef_p,
    "Model_LLR_p": LLR_p,
    "N": observations
})

correct_summary_actors

,Model,Outcome,Subgroup,Formula,Predictor,Coef,Std_err,Coef_p,Model_LLR_p,N
0,RC1_A,resolved_correct,Actors,resolved_correct ~ Agent,Agent,-3.340000e-01,0.419,0.426,0.4242,96
1,RC2_A,resolved_correct,Actors,resolved_correct ~ Goal_Type,goal_non_frequent,-4.590000e-01,0.516,0.374,0.2008,96
2,RC2_A,resolved_correct,Actors,resolved_correct ~ Goal_Type,no_goal,-9.137000e-01,0.516,0.077,0.2008,96
3,RC3_A,resolved_correct,Actors,resolved_correct ~ Agent + Goal_Type,goal_non_frequent,-4.565000e-01,0.519,0.379,0.2559,96
4,RC3_A,resolved_correct,Actors,resolved_correct ~ Agent + Goal_Type,no_goal,-9.480000e-01,0.521,0.069,0.2559,96
5,RC3_A,resolved_correct,Actors,resolved_correct ~ Agent + Goal_Type,Agent,-3.917000e-01,0.429,0.361,0.2559,96
6,RC4_A,resolved_correct,Actors,resolved_correct ~ Agent * Goal_Type,goal_non_frequent,6.475000e-16,0.713,1.000,0.2725,96
7,RC4_A,resolved_correct,Actors,resolved_correct ~ Agent * Goal_Type,no_goal,-1.167600e+00,0.698,0.094,0.2725,96
8,RC4_A,resolved_correct,Actors,resolved_correct ~ Agent * Goal_Type,Agent,-2.513000e-01,0.735,0.732,0.2725,96
9,RC4_A,resolved_correct,Actors,resolved_correct ~ Agent * Goal_Type,Agent:goal_non_frequent,-1.011600e+00,1.065,0.342,0.2725,96
10,RC4_A,resolved_correct,Actors,resolved_correct ~ Agent * Goal_Type,Agent:no_goal,5.798000e-01,1.041,0.578,0.2725,96