# Combined Subgroup: Correct Resolution Model

Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Combined Subgroup

1. Create resolved_correct
2. Counts and Proportions
3. Logistic Models
    
    Main Effect Models:

    - RC01: Focus
    - RC02: Agent
    - RC03: Goal_Type

    Additive Models:

    - RC04: Focus + Agent
    - RC05: Focus + Goal_Type
    - RC06: Agent + Goal_Type

    Interactive Models:

    - RC07: Focus * Agent
    - RC08: Focus * Goal_Type
    - RC09: Agent * Goal_Type
    - RC10: Focus * Agent + Goal_Type
4. Model Comparisons
5. Summary Table

Read Data

In [2]:
subgroup_theoretical = pd.read_csv("../../data/processed/subgroup_theoretical.csv")

1. Create resolved_correct

Binary Outcome: include correct responses from escape_L2 observations.

In [3]:
subgroup_theoretical["escape_L2"] = (
    subgroup_theoretical["Response_Full"] != "L2_other"
).astype(int)

In [4]:
escapees = subgroup_theoretical[subgroup_theoretical["escape_L2"] == 1].copy()

In [5]:
escapees["resolved_correct"] = (escapees["Response_Full"] == "correct").astype(int)

2. Counts and Proportions

In [6]:
resolved_correct_counts = pd.crosstab(
    escapees["resolved_correct"],
    escapees["Response_Full"])

resolved_correct_counts

Response_Full     L1_transfer  correct  missing_response
resolved_correct
0                          96        0                 3
1                           0       61                 0

In [7]:
resolved_correct_props = escapees["resolved_correct"].value_counts(normalize = True)
resolved_correct_props

resolved_correct
0    0.61875
1    0.38125
Name: proportion, dtype: float64

From 160 observations, almost 38% of responses that had escaped *L2_other* options were resolved correctly.

Counts and Proportions by Condition:

In [8]:
counts_condition = pd.crosstab(
    [escapees["Goal_Type"], escapees["Agent"], escapees["Focus"]],
    escapees["resolved_correct"],
    margins = True)

counts_condition

resolved_correct                0   1  All
Goal_Type         Agent Focus
goal_frequent     0     I       7   9   16
                        They    7   5   12
                  1     I       7   7   14
                        They    5   3    8
goal_non_frequent 0     I       7   9   16
                        They   14   3   17
                  1     I      11   4   15
                        They    5   3    8
no_goal           0     I      15   6   21
                        They   10   3   13
                  1     I       9   5   14
                        They    2   4    6
All                            99  61  160

In [9]:
props_condition = pd.crosstab(
    [escapees["Goal_Type"], escapees["Agent"], escapees["Focus"]],
    escapees["resolved_correct"],
    normalize= "index")

props_condition

resolved_correct                      0         1
Goal_Type         Agent Focus
goal_frequent     0     I      0.437500  0.562500
                        They   0.583333  0.416667
                  1     I      0.500000  0.500000
                        They   0.625000  0.375000
goal_non_frequent 0     I      0.437500  0.562500
                        They   0.823529  0.176471
                  1     I      0.733333  0.266667
                        They   0.625000  0.375000
no_goal           0     I      0.714286  0.285714
                        They   0.769231  0.230769
                  1     I      0.642857  0.357143
                        They   0.333333  0.666667

COMMENT GENERAL PROPORTIONS

3. Logistic Models

Import Libraries

In [10]:
import statsmodels.formula.api as smf
from scipy.stats import chi2

In [11]:
escapees["resolved_correct"].value_counts()

resolved_correct
0    99
1    61
Name: count, dtype: int64

**Main Effect Models**

**RC01**

resolved_correct ~ Focus

In [12]:
RC01 = smf.logit(
    "resolved_correct ~ Focus",
    data=escapees
    ).fit()

print(RC01.summary())

Optimization terminated successfully.
         Current function value: 0.660653
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      158
Method:                           MLE   Df Model:                            1
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:                0.006048
Time:                        12:18:09   Log-Likelihood:                -105.70
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.2567
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -0.3365      0.207     -1.625      0.104      -0.742       0.069
Focus[T.They]    -0.3802      0.337     -1.127      0.260      -1.041       0.281
=================================================================================

**RC02**

resolved_correct ~ Agent

In [13]:
RC02 = smf.logit(
    "resolved_correct ~ Agent",
    data=escapees
    ).fit()

print(RC02.summary())

Optimization terminated successfully.
         Current function value: 0.664164
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      158
Method:                           MLE   Df Model:                            1
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:               0.0007657
Time:                        12:18:09   Log-Likelihood:                -106.27
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.6865
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.5390      0.213     -2.534      0.011      -0.956      -0.122
Agent          0.1335      0.331      0.404      0.686      -0.515       0.782
==============================================================================

**RC03**

resolved_correct ~ Goal_Type

In [14]:
RC03 = smf.logit(
    "resolved_correct ~ Goal_Type",
    data= escapees
    ).fit()

print(RC03.summary())

Optimization terminated successfully.
         Current function value: 0.655378
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      157
Method:                           MLE   Df Model:                            2
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:                 0.01398
Time:                        12:18:09   Log-Likelihood:                -104.86
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.2260
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         -0.0800      0.283     -0.283      0.777      -0.635       0.475
Goal_Type[T.goal_non_frequent]    -0.5864      0.400     -1.467      0.142      -1.370       0.197
Goal_Type[T.no_goal]              -0.6131      0.404     -1.516      0.129      -1.406       0.179
==================================================================================================

**RC04**

resolved_correct ~ Focus + Agent

In [15]:
RC04 = smf.logit(
    "resolved_correct ~ Focus + Agent",
    data=escapees
    ).fit()

print(RC04.summary())

Optimization terminated successfully.
         Current function value: 0.660393
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      157
Method:                           MLE   Df Model:                            2
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:                0.006440
Time:                        12:18:09   Log-Likelihood:                -105.66
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.5042
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        -0.3798      0.256     -1.483      0.138      -0.882       0.122
Focus[T.They]    -0.3703      0.339     -1.092      0.275      -1.035       0.294
Agent             0.0964      0.334      0.289      0.773      -0.557       0.750
=================================================================================

**RC05**

resolved_correct ~ Focus + Goal_Type

In [16]:
RC05 = smf.logit(
    "resolved_correct ~ Focus + Goal_Type",
    data=escapees
    ).fit()

print(RC05.summary())

Optimization terminated successfully.
         Current function value: 0.651218
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      156
Method:                           MLE   Df Model:                            3
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:                 0.02024
Time:                        12:18:09   Log-Likelihood:                -104.19
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.2303
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                          0.0757      0.315      0.240      0.810      -0.541       0.692
Focus[T.They]                     -0.3917      0.342     -1.147      0.252      -1.061       0.278
Goal_Type[T.goal_non_frequent]    -0.5735      0.402     -1.428      0.153      -1.360       0.214
Goal_Type[T.no_goal]              -0.6370      0.407     -1.566      0.117      -1.434       0.160
==================================================================================================

**RC06**

resolved_correct ~ Agent + Goal_Type

In [17]:
RC06 = smf.logit(
    "resolved_correct ~ Agent + Goal_Type",
    data= escapees
    ).fit()

print(RC06.summary())

Optimization terminated successfully.
         Current function value: 0.655049
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      156
Method:                           MLE   Df Model:                            3
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:                 0.01448
Time:                        12:18:09   Log-Likelihood:                -104.81
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.3795
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         -0.1279      0.319     -0.401      0.689      -0.754       0.498
Goal_Type[T.goal_non_frequent]    -0.5837      0.400     -1.459      0.144      -1.368       0.200
Goal_Type[T.no_goal]              -0.6059      0.405     -1.496      0.135      -1.400       0.188
Agent                              0.1086      0.334      0.325      0.745      -0.547       0.764
==================================================================================================

**RC07**

resolved_correct ~ Focus * Agent

In [18]:
RC07 = smf.logit(
    "resolved_correct ~ Focus * Agent",
    data= escapees
    ).fit()

print(RC07.summary())

Optimization terminated successfully.
         Current function value: 0.651207
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      156
Method:                           MLE   Df Model:                            3
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:                 0.02026
Time:                        12:18:09   Log-Likelihood:                -104.19
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.2300
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept              -0.1892      0.276     -0.686      0.493      -0.730       0.352
Focus[T.They]          -0.8468      0.446     -1.897      0.058      -1.722       0.028
Agent                  -0.3340      0.419     -0.797      0.426      -1.156       0.488
Focus[T.They]:Agent     1.1878      0.694      1.711      0.087      -0.173       2.549
=======================================================================================

**RC08**

resolved_correct ~ Focus * Goal_Type

In [19]:
RC08 = smf.logit(
    "resolved_correct ~ Focus * Goal_Type",
    data= escapees
    ).fit()

print(RC08.summary())

Optimization terminated successfully.
         Current function value: 0.645866
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      154
Method:                           MLE   Df Model:                            5
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:                 0.02829
Time:                        12:18:09   Log-Likelihood:                -103.34
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.3045
================================================================================================================
                                                   coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
Intercept                                        0.1335      0.366      0.365      0.715      -0.584       0.851
Focus[T.They]                                   -0.5390      0.585     -0.921      0.357      -1.686       0.608
Goal_Type[T.goal_non_frequent]                  -0.4590      0.516     -0.889      0.374      -1.471       0.553
Goal_Type[T.no_goal]                            -0.9137      0.516     -1.770      0.077      -1.926       0.098
Focus[T.They]:Goal_Type[T.goal_non_frequent]    -0.2883      0.833     -0.346      0.729      -1.921       1.345
Focus[T.They]:Goal_Type[T.no_goal]               0.7802      0.837      0.932      0.351      -0.861       2.421
================================================================================================================

**RC09**

resolved_correct ~ Agent * Goal_Type

In [20]:
RC09 = smf.logit(
    "resolved_correct ~ Agent * Goal_Type",
    data=escapees
    ).fit()

print(RC09.summary())

Optimization terminated successfully.
         Current function value: 0.648393
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      154
Method:                           MLE   Df Model:                            5
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:                 0.02449
Time:                        12:18:09   Log-Likelihood:                -103.74
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.3909
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                            -5.629e-17      0.378  -1.49e-16      1.000      -0.741       0.741
Goal_Type[T.goal_non_frequent]          -0.5596      0.523     -1.069      0.285      -1.585       0.466
Goal_Type[T.no_goal]                    -1.0217      0.542     -1.884      0.060      -2.084       0.041
Agent                                   -0.1823      0.571     -0.319      0.750      -1.302       0.937
Agent:Goal_Type[T.goal_non_frequent]    -0.0847      0.814     -0.104      0.917      -1.680       1.511
Agent:Goal_Type[T.no_goal]               1.0033      0.824      1.217      0.223      -0.612       2.619
========================================================================================================

**RC10**

resolved_correct ~ Focus * Agent + Goal_Type

In [21]:
RC10 = smf.logit(
    "resolved_correct ~ Focus * Agent + Goal_Type",
    data=escapees
    ).fit()

print(RC10.summary())

Optimization terminated successfully.
         Current function value: 0.642181
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:       resolved_correct   No. Observations:                  160
Model:                          Logit   Df Residuals:                      154
Method:                           MLE   Df Model:                            5
Date:                Sun, 19 Jul 2026   Pseudo R-squ.:                 0.03384
Time:                        12:18:09   Log-Likelihood:                -102.75
converged:                       True   LL-Null:                       -106.35
Covariance Type:            nonrobust   LLR p-value:                    0.2064
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                          0.2288      0.371      0.616      0.538      -0.499       0.957
Focus[T.They]                     -0.8597      0.452     -1.901      0.057      -1.746       0.026
Goal_Type[T.goal_non_frequent]    -0.5539      0.405     -1.366      0.172      -1.348       0.241
Goal_Type[T.no_goal]              -0.6386      0.411     -1.553      0.121      -1.445       0.168
Agent                             -0.3599      0.424     -0.848      0.396      -1.191       0.472
Focus[T.They]:Agent                1.1814      0.701      1.684      0.092      -0.193       2.556
==================================================================================================

4. Model Comparisons

In [22]:
from scipy.stats import chi2

def lr_test(model_small, model_large):

    LR = 2 * (model_large.llf - model_small.llf)

    df = model_large.df_model - model_small.df_model

    p = chi2.sf(LR, df)

    return pd.Series({
        "LR": LR,
        "df": df,
        "p_value": p
    })

In [23]:
lr_test(RC1, RC3)

NameError: name 'RC1' is not defined

In [ ]:
lr_test(RC1, RC4)

LR         5.046581
df         4.000000
p_value    0.282551
dtype: float64

5. Summary Table

In [ ]:
goal_behaviour = ["Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined"]

model_name = ["RC01", "RC02", "RC03", "RC03", "RC04", "RC04", "RC05", "RC05", "RC05", "RC06", "RC06", "RC06", "RC07", "RC07", "RC07", "RC08", "RC08", "RC08", "RC08", "RC08", "RC09", "RC09", "RC09", "RC09", "RC09", "RC10", "RC10", "RC10", "RC10", "RC10"]

outcome = ["resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct", "resolved_correct"]

formula = ["resolved_correct ~ Focus", "resolved_correct ~ Agent", "resolved_correct ~ Goal_Type", "resolved_correct ~ Goal_Type", "resolved_correct ~ Focus + Agent", "resolved_correct ~ Focus + Agent", "resolved_correct ~ Focus + Goal_Type","resolved_correct ~ Focus + Goal_Type", "resolved_correct ~ Focus + Goal_Type", "resolved_correct ~ Agent + Goal_Type", "resolved_correct ~ Agent + Goal_Type", "resolved_correct ~ Agent + Goal_Type", "resolved_correct ~ Focus * Agent", "resolved_correct ~ Focus * Agent", "resolved_correct ~ Focus * Agent", "resolved_correct ~ Focus * Goal_Type", "resolved_correct ~ Focus * Goal_Type", "resolved_correct ~ Focus * Goal_Type", "resolved_correct ~ Focus * Goal_Type", "resolved_correct ~ Focus * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Agent * Goal_Type", "resolved_correct ~ Focus * Agent + Goal_Type", "resolved_correct ~ Focus * Agent + Goal_Type", "resolved_correct ~ Focus * Agent + Goal_Type", "resolved_correct ~ Focus * Agent + Goal_Type", "resolved_correct ~ Focus * Agent + Goal_Type"]

predictor= ["They", "Agent", "goal_non_frequent", "no_goal", "They", "Agent", "They", "goal_non_frequent", "no_goal", "goal_non_frequent", "no_goal", "Agent", "They", "Agent", "They:Agent", "They", "goal_non_frequent", "no_goal", "They:goal_non_frequent", "They:no_goal", "goal_non_frequent", "no_goal", "Agent", "Agent:goal_non_frequent", "Agent:no_goal", "They", "goal_non_frequent", "no_goal", "Agent", "They:Agent"]

coef = ["RC01", 0.1335, -0.5864, -0.6131, "RC04", "RC04", "RC05", "RC05", "RC05", -0.5837, -0.6059, 0.1086, "RC07", "RC07", "RC07", "RC08", "RC08", "RC08", "RC08", "RC08", -0.5596, -1.0217, -0.1823, -0.0847, 1.0033, "RC10", "RC10", "RC10", "RC10", "RC10"]

std_error = ["RC01", 0.331, 0.400, 0.404, "RC04", "RC04", "RC05", "RC05", "RC05", 0.400, 0.405, 0.334, "RC07", "RC07", "RC07", "RC08", "RC08", "RC08", "RC08", "RC08", 0.523, 0.542, 0.571, 0.814, 0.824, "RC10", "RC10", "RC10", "RC10", "RC10"]

coef_p = ["RC01", 0.686, 0.142, 0.129, "RC04", "RC04", "RC05", "RC05", "RC05", 0.144, 0.135, 0.745, "RC07", "RC07", "RC07", "RC08", "RC08", "RC08", "RC08", "RC08", 0.285, 0.060, 0.750, 0.917, 0.223, "RC10", "RC10", "RC10", "RC10", "RC10"]

LLR_p = ["RC01", 0.6865, 0.2260, 0.2260, "RC04", "RC04", "RC05", "RC05", "RC05", 0.3795, 0.3795, 0.3795, "RC07", "RC07", "RC07", "RC08", "RC08", "RC08", "RC08", "RC08", 0.3909, 0.3909, 0.3909, 0.3909, 0.3909, "RC10", "RC10", "RC10", "RC10", "RC10"]

observations= [160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160]

correct_summary = pd.DataFrame({
    "Goal_Behaviour": goal_behaviour,
    "Model": model_name,
    "Outcome": outcome,
    "Formula": formula, 
    "Predictor": predictor,
    "Coef": coef,
    "Std_err": std_error,
    "Coef_p": coef_p,
    "Model_LLR_p": LLR_p,
    "N": observations
})

correct_summary