# Combined Subgroup: Transfer Resolution Model

Import Libraries

In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Combined Subgroup

1. Create resolved_transfer
2. Counts and Proportions
3. Logistic Models
    
    Main Effect Models:

    - RT01: Focus
    - RT02: Agent
    - RT03: Goal_Type

    Additive Models:

    - RT04: Focus + Agent
    - RT05: Focus + Goal_Type
    - RT06: Agent + Goal_Type

    Interactive Models:

    - RT07: Focus * Agent
    - RT08: Focus * Goal_Type
    - RT09: Agent * Goal_Type
    - RT10: Focus * Agent + Goal_Type
4. Model Comparisons
5. Summary Table

Read Data

In [54]:
subgroup_theoretical = pd.read_csv("../../data/processed/subgroup_theoretical.csv")

1. Create resolved_transfer

Binary Outcome: include L1_transfer responses from escape_L2 observations.

In [55]:
subgroup_theoretical["escape_L2"] = (
    subgroup_theoretical["Response_Full"] != "L2_other"
).astype(int)

In [56]:
escapees = subgroup_theoretical[subgroup_theoretical["escape_L2"] == 1].copy()

In [57]:
escapees["resolved_transfer"] = (escapees["Response_Full"] == "L1_transfer").astype(int)

2. Counts and Proportions

In [58]:
resolved_transfer_counts = pd.crosstab(
    escapees["resolved_transfer"],
    escapees["Response_Full"])

resolved_transfer_counts

Response_Full      L1_transfer  correct  missing_response
resolved_transfer
0                            0       61                 3
1                           96        0                 0

In [59]:
resolved_transfer_props = escapees["resolved_transfer"].value_counts(normalize = True)
resolved_transfer_props

resolved_transfer
1    0.6
0    0.4
Name: proportion, dtype: float64

From 160 observations, 60% of responses that had escaped *L2_other* options were resolved by restoring to L1_transfer.

Counts and Proportions by Condition:

In [60]:
counts_condition = pd.crosstab(
    [escapees["Goal_Type"], escapees["Agent"], escapees["Focus"]],
    escapees["resolved_transfer"],
    margins = True)

counts_condition

resolved_transfer               0   1  All
Goal_Type         Agent Focus
goal_frequent     0     I      10   6   16
                        They    5   7   12
                  1     I       7   7   14
                        They    3   5    8
goal_non_frequent 0     I       9   7   16
                        They    3  14   17
                  1     I       4  11   15
                        They    3   5    8
no_goal           0     I       8  13   21
                        They    3  10   13
                  1     I       5   9   14
                        They    4   2    6
All                            64  96  160

In [61]:
props_condition = pd.crosstab(
    [escapees["Goal_Type"], escapees["Agent"], escapees["Focus"]],
    escapees["resolved_transfer"],
    normalize= "index")

props_condition

resolved_transfer                     0         1
Goal_Type         Agent Focus
goal_frequent     0     I      0.625000  0.375000
                        They   0.416667  0.583333
                  1     I      0.500000  0.500000
                        They   0.375000  0.625000
goal_non_frequent 0     I      0.562500  0.437500
                        They   0.176471  0.823529
                  1     I      0.266667  0.733333
                        They   0.375000  0.625000
no_goal           0     I      0.380952  0.619048
                        They   0.230769  0.769231
                  1     I      0.357143  0.642857
                        They   0.666667  0.333333

COMMENT GENERAL PROPORTIONS

3. Logistic Models

Import Libraries

In [62]:
import statsmodels.formula.api as smf
from scipy.stats import chi2

In [63]:
escapees["resolved_transfer"].value_counts()

resolved_transfer
1    96
0    64
Name: count, dtype: int64

**Main Effects Models**

**RT01**

resolved_transfer ~ Focus

In [64]:
RT01 = smf.logit(
    "resolved_transfer ~ Focus",
    data=escapees
    ).fit()

print(RT01.summary())

Optimization terminated successfully.
         Current function value: 0.665764
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      158
Method:                           MLE   Df Model:                            1
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:                 0.01077
Time:                        21:08:49   Log-Likelihood:                -106.52
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                    0.1278
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.2091      0.205      1.019      0.308      -0.193       0.611
Focus[T.They]     0.5076      0.336      1.510      0.131      -0.151       1.166
=================================================================================

**RT02**

resolved_transfer ~ Agent

In [65]:
RT02 = smf.logit(
    "resolved_transfer ~ Agent",
    data=escapees
    ).fit()

print(RT02.summary())

Optimization terminated successfully.
         Current function value: 0.673012
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      158
Method:                           MLE   Df Model:                            1
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:               1.359e-10
Time:                        21:08:49   Log-Likelihood:                -107.68
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                    0.9999
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.4055      0.209      1.936      0.053      -0.005       0.816
Agent      -9.339e-16      0.329  -2.84e-15      1.000      -0.644       0.644
==============================================================================

**RT03**

resolved_transfer ~ Goal_Type

In [66]:
RT03 = smf.logit(
    "resolved_transfer ~ Goal_Type",
    data=escapees
    ).fit()

print(RT03.summary())

Optimization terminated successfully.
         Current function value: 0.663269
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      157
Method:                           MLE   Df Model:                            2
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:                 0.01448
Time:                        21:08:49   Log-Likelihood:                -106.12
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                    0.2104
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                      -1.852e-16      0.283  -6.55e-16      1.000      -0.554       0.554
Goal_Type[T.goal_non_frequent]     0.6665      0.400      1.668      0.095      -0.117       1.450
Goal_Type[T.no_goal]               0.5306      0.399      1.329      0.184      -0.252       1.313
==================================================================================================

**Additive Models**

**RT04**

resolved_transfer ~ Focus + Agent

In [67]:
RT04 = smf.logit(
    "resolved_transfer ~ Focus + Agent",
    data=escapees
    ).fit()

print(RT04.summary())

Optimization terminated successfully.
         Current function value: 0.665685
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      157
Method:                           MLE   Df Model:                            2
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:                 0.01089
Time:                        21:08:49   Log-Likelihood:                -106.51
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                    0.3097
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.1854      0.253      0.732      0.464      -0.311       0.682
Focus[T.They]     0.5132      0.338      1.518      0.129      -0.149       1.176
Agent             0.0530      0.333      0.159      0.873      -0.599       0.705
=================================================================================

**RT05**

resolved_transfer ~ Focus + Goal_Type

In [68]:
RT05 = smf.logit(
    "resolved_transfer ~ Focus + Goal_Type",
    data=escapees
    ).fit()

print(RT05.summary())

Optimization terminated successfully.
         Current function value: 0.656088
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      156
Method:                           MLE   Df Model:                            3
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:                 0.02515
Time:                        21:08:49   Log-Likelihood:                -104.97
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                    0.1438
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         -0.2042      0.315     -0.647      0.517      -0.823       0.414
Focus[T.They]                      0.5119      0.341      1.503      0.133      -0.156       1.179
Goal_Type[T.goal_non_frequent]     0.6528      0.403      1.622      0.105      -0.136       1.442
Goal_Type[T.no_goal]               0.5631      0.403      1.397      0.162      -0.227       1.353
==================================================================================================

**RT06**

resolved_transfer ~ Agent + Goal_Type

In [69]:
RT06 = smf.logit(
    "resolved_transfer ~ Agent + Goal_Type",
    data= escapees
    ).fit()

print(RT06.summary())

Optimization terminated successfully.
         Current function value: 0.663253
         Iterations 4
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      156
Method:                           MLE   Df Model:                            3
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:                 0.01450
Time:                        21:08:49   Log-Likelihood:                -106.12
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                    0.3731
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         -0.0103      0.318     -0.032      0.974      -0.634       0.614
Goal_Type[T.goal_non_frequent]     0.6672      0.400      1.669      0.095      -0.116       1.451
Goal_Type[T.no_goal]               0.5323      0.400      1.331      0.183      -0.252       1.316
Agent                              0.0233      0.332      0.070      0.944      -0.628       0.675
==================================================================================================

**Interactive Models**

**RT07**

resolved_transfer ~ Focus * Agent

In [70]:
RT07 = smf.logit(
    "resolved_transfer ~ Focus * Agent",
    data=escapees
    ).fit()

print(RT07.summary())

Optimization terminated successfully.
         Current function value: 0.652624
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      156
Method:                           MLE   Df Model:                            3
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:                 0.03029
Time:                        21:08:49   Log-Likelihood:                -104.42
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                   0.08872
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept              -0.0377      0.275     -0.137      0.891      -0.576       0.501
Focus[T.They]           1.0738      0.446      2.409      0.016       0.200       1.947
Agent                   0.5610      0.418      1.341      0.180      -0.259       1.381
Focus[T.They]:Agent    -1.4148      0.694     -2.039      0.041      -2.775      -0.055
=======================================================================================

**RT08**

resolved_transfer ~ Focus * Goal_Type

In [71]:
RT08 = smf.logit(
    "resolved_transfer ~ Focus * Goal_Type",
    data=escapees
    ).fit()

print(RT08.summary())

Optimization terminated successfully.
         Current function value: 0.652755
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      154
Method:                           MLE   Df Model:                            5
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:                 0.03010
Time:                        21:08:49   Log-Likelihood:                -104.44
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                    0.2621
================================================================================================================
                                                   coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------
Intercept                                       -0.2683      0.368     -0.728      0.467      -0.990       0.454
Focus[T.They]                                    0.6737      0.587      1.149      0.251      -0.476       1.823
Goal_Type[T.goal_non_frequent]                   0.5937      0.518      1.146      0.252      -0.421       1.609
Goal_Type[T.no_goal]                             0.7944      0.508      1.564      0.118      -0.201       1.790
Focus[T.They]:Goal_Type[T.goal_non_frequent]     0.1535      0.834      0.184      0.854      -1.481       1.788
Focus[T.They]:Goal_Type[T.no_goal]              -0.6608      0.832     -0.794      0.427      -2.292       0.970
================================================================================================================

**RT09**

resolved_transfer ~ Agent * Goal_Type

In [72]:
RT09 = smf.logit(
    "resolved_transfer ~ Agent * Goal_Type",
    data=escapees
    ).fit()

print(RT09.summary())

Optimization terminated successfully.
         Current function value: 0.658907
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      154
Method:                           MLE   Df Model:                            5
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:                 0.02096
Time:                        21:08:49   Log-Likelihood:                -105.43
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                    0.4781
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                               -0.1431      0.379     -0.378      0.706      -0.886       0.600
Goal_Type[T.goal_non_frequent]           0.7027      0.524      1.341      0.180      -0.324       1.730
Goal_Type[T.no_goal]                     0.8807      0.527      1.670      0.095      -0.153       1.914
Agent                                    0.3254      0.572      0.569      0.569      -0.795       1.446
Agent:Goal_Type[T.goal_non_frequent]    -0.0584      0.814     -0.072      0.943      -1.655       1.538
Agent:Goal_Type[T.no_goal]              -0.8624      0.814     -1.059      0.290      -2.459       0.734
========================================================================================================

**RT10**

resolved_transfer ~ Focus * Agent + Goal_Type

In [73]:
RT10 = smf.logit(
    "resolved_transfer ~ Focus * Agent + Goal_Type",
    data=escapees
    ).fit()

print(RT10.summary())

Optimization terminated successfully.
         Current function value: 0.643309
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:      resolved_transfer   No. Observations:                  160
Model:                          Logit   Df Residuals:                      154
Method:                           MLE   Df Model:                            5
Date:                Thu, 16 Jul 2026   Pseudo R-squ.:                 0.04413
Time:                        21:08:49   Log-Likelihood:                -102.93
converged:                       True   LL-Null:                       -107.68
Covariance Type:            nonrobust   LLR p-value:                   0.09055
==================================================================================================
                                     coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
Intercept                         -0.4614      0.374     -1.232      0.218      -1.195       0.272
Focus[T.They]                      1.0783      0.451      2.389      0.017       0.194       1.963
Goal_Type[T.goal_non_frequent]     0.6374      0.408      1.563      0.118      -0.162       1.437
Goal_Type[T.no_goal]               0.5781      0.410      1.411      0.158      -0.225       1.381
Agent                              0.5835      0.424      1.377      0.168      -0.247       1.414
Focus[T.They]:Agent               -1.4047      0.701     -2.003      0.045      -2.779      -0.030
==================================================================================================

4. Model Comparisons

In [74]:
from scipy.stats import chi2

def lr_test(model_small, model_large):

    LR = 2 * (model_large.llf - model_small.llf)

    df = model_large.df_model - model_small.df_model

    p = chi2.sf(LR, df)

    return pd.Series({
        "LR": LR,
        "df": df,
        "p_value": p
    })

In [75]:
lr_test(RT1, RT3)

LR         3.122680
df         2.000000
p_value    0.209855
dtype: float64

In [76]:
lr_test(RT1, RT4)

LR         4.513476
df         4.000000
p_value    0.340953
dtype: float64

5. Summary Table

In [77]:
goal_behaviour = ["Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined", "Combined"]

model_name = ["RT1", "RT2", "RT2", "RT3", "RT3", "RT3", "RT4", "RT4", "RT4", "RT4", "RT4"]

outcome = ["resolved_transfer","resolved_transfer", "resolved_transfer", "resolved_transfer", "resolved_transfer", "resolved_transfer", "resolved_transfer", "resolved_transfer", "resolved_transfer", "resolved_transfer", "resolved_transfer"]

subgroup = ["Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall", "Overall"]

formula = ["resolved_transfer ~ Agent", "resolved_transfer ~ Goal_Type", "resolved_transfer ~ Goal_Type", "resolved_transfer ~ Agent + Goal_Type", "resolved_transfer ~ Agent + Goal_Type", "resolved_transfer ~ Agent + Goal_Type", "resolved_transfer ~ Agent * Goal_Type", "resolved_transfer ~ Agent * Goal_Type", "resolved_transfer ~ Agent * Goal_Type", "resolved_transfer ~ Agent * Goal_Type", "resolved_transfer ~ Agent * Goal_Type"]

predictor= ["Agent", "goal_non_frequent", "no_goal", "goal_non_frequent", "no_goal", "Agent",  "goal_non_frequent", "no_goal", "Agent", "Agent:goal_non_frequent", "Agent:no_goal"]

coef = [-9.339e-16, 0.6665, 0.5306, 0.6672, 0.5323, 0.0233, 0.7027, 0.8807, 0.3254, -0.0584, -0.8624]

std_error = [0.329, 0.400, 0.399, 0.400, 0.400, 0.332, 0.524, 0.527, 0.572, 0.814, 0.814]

coef_p = [1.000, 0.095, 0.184, 0.095, 0.183, 0.944, 0.180, 0.095, 0.569, 0.943, 0.290]

LLR_p = [0.999, 0.2104, 0.2104, 0.3731, 0.3731, 0.3731, 0.4781, 0.4781, 0.4781, 0.4781, 0.4781]

observations = [160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160]

Takeaway = []

transfer_summary_overall = pd.DataFrame({
    "Goal_Behaviour": goal_behaviour,
    "Model": model_name,
    "Outcome": outcome,
    "Subgroup": subgroup,
    "Formula": formula, 
    "Predictor": predictor,
    "Coef": coef,
    "Std_err": std_error,
    "Coef_p": coef_p,
    "Model_LLR_p": LLR_p,
    "N": observations
})

transfer_summary_overall